spring.application.name=MatchUp
server.servlet.context-path=/api
#db config not needed because of spring-boot-docker-compose dependency
security.jwt.secret-key=i1uK5u8pV6WmZkH3a2Qb4rT8sXy1nF6j0dMvN9pQ2zA=
security.jwt.expiration-time=3600000